<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: JobParam.proto

namespace GPBMetadata;

class JobParam
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
@
JobParam.proto"&
JobParam
key (	
value (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

