<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Log.proto

namespace GPBMetadata;

class Log
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
u
	Log.proto"`
Log

id (	
log (	
level (	
	timestamp (
source (	
nodeId (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

