<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rpc.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>RpcRequestJob</code>
 */
class RpcRequestJob extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string runOn = 1;</code>
     */
    protected $runOn = '';
    /**
     * Generated from protobuf field <code>uint64 expireAfter = 2;</code>
     */
    protected $expireAfter = 0;
    /**
     * Generated from protobuf field <code>repeated .JobInput input = 3;</code>
     */
    private $input;
    /**
     * Generated from protobuf field <code>repeated .JobParam param = 4;</code>
     */
    private $param;
    /**
     * Generated from protobuf field <code>string description = 6;</code>
     */
    protected $description = '';
    /**
     * Generated from protobuf field <code>optional uint32 kind = 7;</code>
     */
    protected $kind = null;
    /**
     * Generated from protobuf field <code>optional string outputFormat = 8;</code>
     */
    protected $outputFormat = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $runOn
     *     @type int|string $expireAfter
     *     @type array<\JobInput>|\Google\Protobuf\Internal\RepeatedField $input
     *     @type array<\JobParam>|\Google\Protobuf\Internal\RepeatedField $param
     *     @type string $description
     *     @type int $kind
     *     @type string $outputFormat
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Rpc::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string runOn = 1;</code>
     * @return string
     */
    public function getRunOn()
    {
        return $this->runOn;
    }

    /**
     * Generated from protobuf field <code>string runOn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRunOn($var)
    {
        GPBUtil::checkString($var, True);
        $this->runOn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>uint64 expireAfter = 2;</code>
     * @return int|string
     */
    public function getExpireAfter()
    {
        return $this->expireAfter;
    }

    /**
     * Generated from protobuf field <code>uint64 expireAfter = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setExpireAfter($var)
    {
        GPBUtil::checkUint64($var);
        $this->expireAfter = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .JobInput input = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInput()
    {
        return $this->input;
    }

    /**
     * Generated from protobuf field <code>repeated .JobInput input = 3;</code>
     * @param array<\JobInput>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInput($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \JobInput::class);
        $this->input = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .JobParam param = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParam()
    {
        return $this->param;
    }

    /**
     * Generated from protobuf field <code>repeated .JobParam param = 4;</code>
     * @param array<\JobParam>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParam($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \JobParam::class);
        $this->param = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string description = 6;</code>
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Generated from protobuf field <code>string description = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setDescription($var)
    {
        GPBUtil::checkString($var, True);
        $this->description = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional uint32 kind = 7;</code>
     * @return int
     */
    public function getKind()
    {
        return isset($this->kind) ? $this->kind : 0;
    }

    public function hasKind()
    {
        return isset($this->kind);
    }

    public function clearKind()
    {
        unset($this->kind);
    }

    /**
     * Generated from protobuf field <code>optional uint32 kind = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setKind($var)
    {
        GPBUtil::checkUint32($var);
        $this->kind = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string outputFormat = 8;</code>
     * @return string
     */
    public function getOutputFormat()
    {
        return isset($this->outputFormat) ? $this->outputFormat : '';
    }

    public function hasOutputFormat()
    {
        return isset($this->outputFormat);
    }

    public function clearOutputFormat()
    {
        unset($this->outputFormat);
    }

    /**
     * Generated from protobuf field <code>optional string outputFormat = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setOutputFormat($var)
    {
        GPBUtil::checkString($var, True);
        $this->outputFormat = $var;

        return $this;
    }

}

